AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: A RESTful API with Amazon Api Gateway and AWS Lambda
Resources:
    HelloGetFunction:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: nodejs6.10
            Handler: index.handler
            Events:
                HelloApi:
                    Type: Api
                    Properties:
                        Path: /
                        Method: GET



