AWSTemplateFormatVersion: 2010-09-09
Description: >-
    This template runs the nested infrastructure-* templates, and creates a
    VPC, and Application Load Balancer, and an ECS Cluster.
Parameters:
    KeyPairName:
        Type: AWS::EC2::KeyPair::KeyName
        Description: >-
            Name of the SSH keypair, to allow to you to login to ECS cluster intances.
Resources:
    VPCStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: ./infrastructure-vpc.template.json
            Parameters:
                KeyPairName: !Ref KeyPairName
                NumberOfAZs: 2
                AvailabilityZones:
                    Fn::Join:
                        - ","
                        -
                            - Fn::Select:
                                - 0
                                - !GetAZs ""
                            - Fn::Select:
                                - 1
                                - !GetAZs ""
                CreatePrivateSubnets: "true"
                NATInstanceType: t2.micro
    ALBStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: ./infrastructure-alb.template.yml
            Parameters:
                Name: !Ref AWS::StackName
                VPCID: !GetAtt VPCStack.Outputs.VPCID
                SubnetIDs:
                    Fn::Join:
                        - ","
                        -
                            - !GetAtt VPCStack.Outputs.PublicSubnet1ID
                            - !GetAtt VPCStack.Outputs.PublicSubnet2ID
    ECSStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: ./infrastructure-ecs.template.yml
            Parameters:
                VPCID: !GetAtt VPCStack.Outputs.VPCID
                KeyPairName: !Ref KeyPairName
                DesiredCapacity: 2
                ECSInstanceType: t2.small
                LoadBalancerSecurityGroupID: !GetAtt ALBStack.Outputs.LoadBalancerSecurityGroupID
                SubnetIDs:
                    Fn::Join:
                        - ","
                        -
                            - !GetAtt VPCStack.Outputs.PrivateSubnet1AID
                            - !GetAtt VPCStack.Outputs.PrivateSubnet2AID
Outputs:
    VPCID:
        Value: !GetAtt VPCStack.Outputs.VPCID
        Description: ID of the VPC created.
        Export:
            Name: !Sub ${AWS::StackName}-VPCID
    LoadBalancerDNSName:
        Value: !GetAtt ALBStack.Outputs.LoadBalancerDNSName
        Description: Hostname of the Load Balancer
        Export:
            Name: !Sub ${AWS::StackName}-LoadBalancerDNSName
    LoadBalancerArn:
        Value: !GetAtt ALBStack.Outputs.LoadBalancerArn
        Description: ARN of the Load Balancer
        Export:
            Name: !Sub ${AWS::StackName}-LoadBalancerArn
    LoadBalancerListenerArn:
        Value: !GetAtt ALBStack.Outputs.LoadBalancerListenerArn
        Description: ARN of the Load Balancer Port 80 Listener
        Export:
            Name: !Sub ${AWS::StackName}-LoadBalancerListenerArn
    LoadBalancerSecurityGroupID:
        Value: !GetAtt ALBStack.Outputs.LoadBalancerSecurityGroupID
        Description: ID of the Security Group of the Load Balancer
        Export:
            Name: !Sub ${AWS::StackName}-LoadBalancerSecurityGroupID
    ECSClusterName:
        Value: !GetAtt ECSStack.Outputs.ECSClusterName
        Description: Name of the ECS Cluster
        Export:
            Name: !Sub ${AWS::StackName}-ECSClusterName
    ECSClusterArn:
        Value: !GetAtt ECSStack.Outputs.ECSClusterArn
        Description: ECS Cluster Arn
        Export:
            Name: !Sub ${AWS::StackName}-ECSClusterArn
    ECSSecurityGroupID:
        Value: !GetAtt ECSStack.Outputs.ECSSecurityGroupID
        Description: ID of ECS Cluster Security Group
        Export:
            Name: !Sub ${AWS::StackName}-ECSSecurityGroupID
    ECSLaunchConfigurationName:
        Value: !GetAtt ECSStack.Outputs.ECSLaunchConfigurationName
        Description: Name of the Auto-Scaling Launch Configuration used by the ECS cluster auto-scaling group.
        Export:
            Name: !Sub ${AWS::StackName}-ECSLaunchConfigurationName
    ECSAutoScalingGroupName:
        Value: !GetAtt ECSStack.Outputs.ECSAutoScalingGroupName
        Description: Name of the Auto-Scaling Group used to create the ECS cluster.
        Export:
            Name: !Sub ${AWS::StackName}-ECSAutoScalingGroupName

