AWSTemplateFormatVersion: 2010-09-09
Description: >-
    This template runs the nested infrastructure-* templates, and creates a
    VPC, and Application Load Balancer, and an ECS Cluster.
Parameters:
    KeyPairName:
        Type: AWS::EC2::KeyPair::KeyName
        Description: >-
            Name of the SSH keypair, to allow to you to login to ECS cluster intances.
Resources:
    VPCStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: ./infrastructure-vpc.template.json
            Parameters:
                KeyPairName: !Ref KeyPairName
                NumberOfAZs: 2
                AvailabilityZones:
                    Fn::Join:
                        - ","
                        -
                            - Fn::Select:
                                - 0
                                - !GetAZs ""
                            - Fn::Select:
                                - 1
                                - !GetAZs ""
                CreatePrivateSubnets: "true"
                NATInstanceType: t2.micro
    ALBStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: ./infrastructure-alb.template.yml
            Parameters:
                Name: !Ref AWS::StackName
                VPCID: !GetAtt VPCStack.Outputs.VPCID
                SubnetIDs:
                    Fn::Join:
                        - ","
                        -
                            - !GetAtt VPCStack.Outputs.PublicSubnet1ID
                            - !GetAtt VPCStack.Outputs.PublicSubnet2ID
    ECSStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: ./infrastructure-ecs.template.yml
            Parameters:
                VPCID: !GetAtt VPCStack.Outputs.VPCID
                KeyPairName: !Ref KeyPairName
                LoadBalancerSecurityGroupID: !GetAtt ALBStack.Outputs.LoadBalancerSecurityGroupID
                SubnetIDs:
                    Fn::Join:
                        - ","
                        -
                            - !GetAtt VPCStack.Outputs.PrivateSubnet1AID
                            - !GetAtt VPCStack.Outputs.PrivateSubnet2AID


