AWSTemplateFormatVersion: "2010-09-09"
Description: >-
    Created a build pipeline.  Starting from a Java web app and Dockerfile (and
    some helper scripts), builds the app, creates a Docker image, and pushes it
    to an ECR Repository.
Parameters:
    CodePipelineS3BucketName:
        Type: String
        AllowedPattern: "[a-zA-Z0-9\\-\\.]{3,63}"
        Description: >-
            Name of an existing S3 bucket in the same region as the pipeline,
            which is used as an artifact store for all pipelines.  This pipeline
            will create a folder to contain its artifacts based on the name of
            the project.
    AppName:
        Type: String
        AllowedPattern: "[a-z0-9\\-_]{3,50}"
        Description: Friendly name for the app. Will be used for git repository, ECR repository, ECS task and service names, cloudwatch log groups,...
        ConstraintDescription: >-
            Any combination of lowercase letters, numbers, underscores, and dashes between 
            1 and 50 characters in length. Cannot end in .git.  Must begin and end with a letter or number.
Resources:
    CodeCommitRepository:
        Type: AWS::CodeCommit::Repository
        DeletionPolicy: Delete
        Properties:
            RepositoryName: !Ref AppName
    ECRRepository:
        Type: AWS::ECR::Repository
        DeletionPolicy: Delete
        Properties:
            RepositoryName: !Ref AppName
    CloudWatchLogsPolicy:
        Type: AWS::IAM::ManagedPolicy
        DeletionPolicy: Delete
        Properties:
            Description: Shared policy for access to CloudWatch Logs
            PolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Action:
                          - logs:Describe*
                      Resource: "*"
                    - Effect: Allow
                      Resource:
                          - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${AppName}*
                          - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/ecs/${AppName}*
                      Action:
                          - logs:CreateLogGroup
                          - logs:DeleteLogGroup
                          - logs:CreateLogStream
                          - logs:PutLogEvents
                          - logs:PutRetentionPolicy
    CodeBuildIAMRole:
        Type: AWS::IAM::Role
        Metadata:
            Description: The IAM role that the CodeBuild projects will use to access your resources.
        Properties:
            Path: "/"
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Action: sts:AssumeRole
                      Principal:
                          Service: codebuild.amazonaws.com
            ManagedPolicyArns:
                - !Ref CloudWatchLogsPolicy
            Policies:
                - PolicyName: !Sub ${AWS::StackName}-CodeBuild
                  PolicyDocument:
                      Version: 2012-10-17
                      Statement:
                          - Sid: CodeCommitRepositoryAccess
                            Effect: Allow
                            Resource: !GetAtt CodeCommitRepository.Arn
                            Action:
                              - codecommit:GitPull
                          - Sid: CodePipelineS3BucketAccess
                            Effect: Allow
                            Resource: !Sub arn:aws:s3:::${CodePipelineS3BucketName}/*
                            Action:
                                - s3:PutObject
                                - s3:GetObject
                                - s3:GetObjectVersion
                          - Sid: ECRRepositoryAccess
                            Effect: Allow
                            Resource: !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${ECRRepository}
                            Action:
                                - ecr:BatchCheckLayerAvailability
                                - ecr:InitiateLayerUpload
                                - ecr:UploadLayerPart
                                - ecr:CompleteLayerUpload
                                - ecr:PutImage
                          - Sid: ECRRepositoryAuthorizationAccess
                            Effect: Allow
                            Resource: "*"
                            Action: ecr:GetAuthorizationToken
                          - Sid: KMSS3KeyAccess
                            Effect: Allow
                            Action:
                                - kms:Encrypt
                                - kms:Decrypt
                            Resource: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3
    CfnIAMRole:
        Type: AWS::IAM::Role
        Metadata:
            Description: The IAM role that CloudFormation will be using to deploy our app
        Properties:
            Path: "/"
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Action: sts:AssumeRole
                      Principal:
                          Service: cloudformation.amazonaws.com
            ManagedPolicyArns:
                - !Ref CloudWatchLogsPolicy
            Policies:
                - PolicyName: !Sub ${AWS::StackName}-CloudFormation
                  PolicyDocument:
                      Version: 2012-10-17
                      Statement:
                          - Effect: Allow
                            Action:
                                - ec2:Describe*
                                - ecs:CreateService
                                - ecs:DeleteService
                                - ecs:UpdateService
                                - ecs:RegisterTaskDefinition
                                - ecs:DeregisterTaskDefinition
                                - ecs:Describe*
                                - elasticloadbalancing:CreateRule
                                - elasticloadbalancing:CreateTargetGroup
                                - elasticloadbalancing:DeleteRule
                                - elasticloadbalancing:DeleteTargetGroup
                                - elasticloadbalancing:ModifyTargetGroupAttributes
                                - elasticloadbalancing:Describe*
                            Resource: "*"
                          - Effect: Allow
                            Action:
                                - iam:CreateRole
                                - iam:DeleteRole
                                - iam:GetRole
                                - iam:PassRole
                            Resource:
                                - !Sub "arn:aws:iam::${AWS::AccountId}:role/${AWS::StackName}*"
                                - !Sub arn:aws:iam::${AWS::AccountId}:role/ecsServiceRole
    CodePipelineIAMRole:
        Type: AWS::IAM::Role
        Metadata:
            Description: The IAM role that CodePipeline will use to access your resources.
        Properties:
            Path: "/"
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Action: sts:AssumeRole
                      Principal:
                          Service: codepipeline.amazonaws.com
            ManagedPolicyArns:
                - !Ref CloudWatchLogsPolicy
            Policies:
                - PolicyName: !Sub ${AWS::StackName}-CodePipeline
                  PolicyDocument:
                      Version: 2012-10-17
                      Statement:
                          - Sid: CodeCommitRepositoryAccess
                            Effect: Allow
                            Resource: !GetAtt CodeCommitRepository.Arn
                            Action:
                                - codecommit:GetBranch
                                - codecommit:GetCommit
                                - codecommit:UploadArchive
                                - codecommit:GetUploadArchiveStatus
                                - codecommit:CancelUploadArchive
                          - Sid: CodePipelineS3BucketAccess
                            Effect: Allow
                            Resource: !Sub arn:aws:s3:::${CodePipelineS3BucketName}/*
                            Action:
                                - s3:GetObject
                                - s3:PutObject
                          - Sid: CodeBuildProjectsAccess
                            Effect: Allow
                            Resource:
                                - !GetAtt CodeBuildMaven.Arn
                                - !GetAtt CodeBuildDocker.Arn
                            Action:
                                - codebuild:StartBuild
                                - codebuild:BatchGetBuilds
                          - Sid: KMSS3KeyAccess
                            Effect: Allow
                            Action:
                                - kms:Encrypt
                                - kms:Decrypt
                            Resource: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3"
                          - Sid: CfnReadPerms
                            Effect: Allow
                            Action:
                                - cloudformation:DescribeStacks
                                - cloudformation:DescribeChangeSet
                                - cloudformation:ValidateTemplate
                            Resource: "*"
                          - Sid: CfnMutatePerms
                            Effect: Allow
                            Action:
                                - cloudformation:CreateStack
                                - cloudformation:DeleteStack
                                - cloudformation:UpdateStack
                                - cloudformation:SetStackPolicy
                                - cloudformation:CreateChangeSet
                                - cloudformation:DeleteChangeSet
                                - cloudformation:ExecuteChangeSet
                            Resource: !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${AWS::StackName}*"
                          - Sid: IAMPerms
                            Effect: Allow
                            Action:
                                - iam:PassRole
                            Resource:
                                - !GetAtt CfnIAMRole.Arn
                                - !Sub "arn:aws:iam::${AWS::AccountId}:role/ecsServiceRole"

    CodeBuildMaven:
        Type: AWS::CodeBuild::Project
        Description: >-
            Builds the Java project using maven. Packages the JAR, Dockerfile,
            docker build scripts for the next step.
        Properties:
            Name: !Sub ${AppName}-Maven
            Source:
                Type: CODEPIPELINE
                BuildSpec: |
                    version: "0.2"
                    phases:
                        build:
                            commands:
                                - ./make_dist.sh ${IMAGE_REPO_NAME}
                    artifacts:
                        files:
                            - "**/*"
                        base-directory: dist
            Artifacts:
                Type: CODEPIPELINE
            ServiceRole: !GetAtt CodeBuildIAMRole.Arn
            Environment:
                Type: LINUX_CONTAINER
                ComputeType: BUILD_GENERAL1_SMALL
                Image: "aws/codebuild/java:openjdk-8"
                PrivilegedMode: false
                EnvironmentVariables:
                    - Name: IMAGE_REPO_NAME
                      Value: !Ref ECRRepository
    CodeBuildDocker:
        Type: AWS::CodeBuild::Project
        Description: >-
            Creates a Docker image. Uploads image to ECR.  Uses scripts
            provided by previous action.
        Properties:
            Name: !Sub ${AppName}-Docker
            Source:
                Type: CODEPIPELINE
                BuildSpec: |
                    version: "0.2"
                    phases:
                        build:
                            commands:
                                - "./docker/docker_build.sh"
                                - "./docker/ecr_push.sh"
                                - "./docker/write_tag.sh"
                    artifacts:
                        files:
                            - output.json
            Artifacts:
                Type: CODEPIPELINE
            ServiceRole: !GetAtt CodeBuildIAMRole.Arn
            Environment:
                Type: LINUX_CONTAINER
                ComputeType: BUILD_GENERAL1_SMALL
                Image: "aws/codebuild/docker:1.12.1"
                PrivilegedMode: true
                EnvironmentVariables:
                    - Name: AWS_ACCOUNT_ID
                      Value: !Ref AWS::AccountId
                    - Name: AWS_DEFAULT_REGION
                      Value: !Ref AWS::Region
                    - Name: IMAGE_REPO_NAME
                      Value: !Ref ECRRepository
    CodePipeline:
        Type: AWS::CodePipeline::Pipeline
        Properties:
            Name: !Ref AppName
            ArtifactStore:
                Type: S3
                Location: !Ref CodePipelineS3BucketName
            RoleArn: !GetAtt CodePipelineIAMRole.Arn
            RestartExecutionOnUpdate: true
            Stages:
                - Name: Source
                  Actions:
                      - Name: Source
                        ActionTypeId:
                            Category: Source
                            Owner: AWS
                            Provider: CodeCommit
                            Version: "1"
                        OutputArtifacts:
                            - Name: SourceOutput
                        Configuration:
                            PollForSourceChanges: "false"
                            RepositoryName: !GetAtt CodeCommitRepository.Name
                            BranchName: master
                - Name: Build
                  Actions:
                      - Name: Build-Maven
                        RunOrder: 1
                        ActionTypeId:
                            Category: Build
                            Owner: AWS
                            Provider: CodeBuild
                            Version: "1"
                        InputArtifacts:
                            - Name: SourceOutput
                        OutputArtifacts:
                            - Name: CodeBuildMavenOutput
                        Configuration:
                            ProjectName: !Ref CodeBuildMaven
                      - Name: Build-Docker
                        RunOrder: 2
                        ActionTypeId:
                            Category: Build
                            Owner: AWS
                            Provider: CodeBuild
                            Version: "1"
                        InputArtifacts:
                            - Name: CodeBuildMavenOutput
                        OutputArtifacts:
                            - Name: CodeBuildDockerOutput
                        Configuration:
                            ProjectName: !Ref CodeBuildDocker
                - Name: Test
                  Actions:
                      - Name: Test-Deploy
                        RunOrder: 1
                        ActionTypeId:
                            Category: Deploy
                            Owner: AWS
                            Provider: CloudFormation
                            Version:  "1"
                        InputArtifacts:
                            - Name: SourceOutput
                            - Name: CodeBuildDockerOutput
                        OutputArtifacts: 
                            - Name: TestDeployOutput
                        Configuration:
                            ActionMode: REPLACE_ON_FAILURE
                            RoleArn: !GetAtt CfnIAMRole.Arn
                            StackName: !Sub ${AWS::StackName}-test
                            TemplatePath: !Sub "SourceOutput::templates/app.template.yml"
                            TemplateConfiguration: !Sub "SourceOutput::templates/app.configuration.json"
                            Capabilities: CAPABILITY_IAM
                            OutputFileName: cfnoutput.json
                            ParameterOverrides: !Sub |
                                {
                                    "ImageTag": {"Fn::GetParam": ["CodeBuildDockerOutput", "output.json", "tag"]}
                                }
    CWEPipelineIAMRole:
        Type: AWS::IAM::Role
        Metadata:
            Description: Allowed CloudWatch Events (CWE) to start a CodePipeline pipeline
        Properties:
            Path: "/"
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Action: sts:AssumeRole
                      Principal:
                          Service: events.amazonaws.com
            Policies:
                - PolicyName: !Sub ${AWS::StackName}-CloudWatchEvents
                  PolicyDocument:
                      Version: 2012-10-17
                      Statement:
                          - Effect: Allow
                            Resource: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${CodePipeline}
                            Action: codepipeline:StartPipelineExecution
    CodeCommitCloudWatchEvent:
        Type: AWS::Events::Rule
        Properties:
            Name: !Sub ${AWS::StackName}-CodeCommit
            Description: >-
                A CloudWatch Events Rule that will trigger our CodePipeline
                when a commit is made to CodeCommitRepository.
            Targets:
                - Id: !Sub ${AWS::StackName}-CodePipeline
                  Arn: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${CodePipeline}
                  RoleArn: !GetAtt CWEPipelineIAMRole.Arn
            EventPattern:
                source:
                    - aws.codecommit
                resources:
                    - !GetAtt CodeCommitRepository.Arn
                detail-type:
                    - CodeCommit Repository State Change
                detail:
                    event:
                        - referenceCreated
                        - referenceUpdated
                    referenceType:
                        - branch
                    referenceName:
                        - master
Outputs:
    CloneUrlHttp:
        Value: !GetAtt CodeCommitRepository.CloneUrlHttp
        Export:
            Name: !Sub ${AWS::StackName}-CloneUrlHttp
    CodeCommitConsoleUrl:
        Value: !Sub https://console.aws.amazon.com/codecommit/home?region=${AWS::Region}#/repository/${CodeCommitRepository.Name}/browse/HEAD/--/
        Export:
            Name: !Sub ${AWS::StackName}-CodeCommitConsoleUrl
    PipelineConsoleUrl:
        Value: !Sub https://console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/${CodePipeline}
        Export:
            Name: !Sub ${AWS::StackName}-PipelineConsoleUrl
